### PR TITLE
Add support BigDecimal type

### PR DESCRIPTION
**Pull request by arisawa**
T/O
I'm using decimal type column on a garage application.

### CODE REVIEW

**Comment by taiki45** [comment]
I'm not sure, but can Ruby's BigDecimal convert to JSON's Integer?

**Comment by arisawa** [comment]
Thanks for the quick reply.
Yes, I think. Such a thing?
```
[1] pry(main)> { lat: BigDecimal.new("1.23456789") }.to_json
=> "{\"lat\":\"1.23456789\"}"
```

**Comment by taiki45** [comment]
hmm.. BigDecimal is not always mapped to JSON's Integer or Float. Seems to be always mapped to JSON's String. Why don't you convert BigDecimal to String or other types before it converts? Currently I think BigDecimal has less pros to support it.

```
[1] pry(main)> { lat: BigDecimal.new("1.23456789") }.to_json
=> "{\"lat\":\"1.23456789\"}"
[2] pry(main)> {lat: BigDecimal("NaN")}.to_json
=> "{\"lat\":\"NaN\"}"
```

**Comment by arisawa** [comment]
Thanks, I understand. There was no problem in my use case, the response body is converted to Integer.
The following JSON content is generated by autodoc. It's `longitude` value is String.
```
{
  "id": 11,
  "email": "hwatkins-at-bluejam.com",
  "name": "Ann Hall",
  "place": {
    "id": 2,
    "name": "mlynch"
    "latitude": 35.693649,
    "longitude": 0.0
  }
}
```
Why I do not know what will happen, I read `hypermedia_responder.rb` now.

**Comment by arisawa** [comment]
@taiki45 
Certainly it will happen is a problem that it is "NaN". Since developer is necessary to consider, it seems good is better not supported.
I'll make instance method and use it.

Thanks for your great support!

**Comment by taiki45** [comment]
Anytime! :smile:

**Pull request closed without merging**
