### PR TITLE
Split doorkeeper things

### PR DESCRIPTION
**Pull request by taiki45**
related with https://github.com/cookpad/garage/issues/9

## By this change
- Split doorkeeper things from Garage. Does not have codes for doorkeeper and does not depend on doorkeeper gem.
- We can use doorkeeper integration by creating external gem like https://github.com/taiki45/garage-doorkeeper. I will arrange doorkeeper integration gem after this PR merged.
- Enable to select authentication/authorization strategy like delegating to auth server.

## Breaking changes
- Remove no_authentiction feature. Use `Garage::Auth_filter::No_authentication` instread.
- Require console-app secret. Previously, Garage only requires console-app uid.

### CODE REVIEW

**Comment by luvtechno** [comment]
Hello - what does prevent this change being merged? We are in process of assessment of this gem and the change seems one of critical features we will need. 

Let me know if anything I can help to move forward.

**Comment by taiki45** [comment]
This change is like Workaround, does not resolve core problem (splitting authentication/authorization logic).

What is your "one of critical features"? I want not to remove the feature which user heavily depends.

**Comment by luvtechno** [comment]
Hm. What we really need is delegating user authentication/authorization to a separate   server dedicated to auth. 

I was under impression this change will be a step towards decoupling user auth via  embedded Doorkeeper... 

Does this answer to your question?

**Comment by taiki45** [comment]
@luvtechno Yes. I understood you want the feature "Enable to select authentication/authorization strategy like delegating to auth server". I raise priority of this issue.

**Comment by taiki45** [comment]
I refactored some codes, and add `Garage::AuthFilter::AuthServer` filter to delegate authentication/authorization to OAuth server, and add documents about auth filters.

I will arrange doorkeeper integration gem after this PR merged because the gem needs new version of Garage.

Drop `WIP`. Please review this :eyeglasses:

**Comment by taiki45** [comment]
I renamed ambiguous AuthFilter to AuthenticationStrategy.

**Comment by luvtechno** [comment]
thanks ---- will try it out

**Comment by taiki45** [comment]
Tell me or issue if you have any bugs or requests.

**Pull request merged**
