### PR TITLE
add support Time type

### PR DESCRIPTION
**Pull request by y-yagi**
T/O

### CODE REVIEW

**Comment by taiki45** [comment]
Thank you.

**Comment by y-yagi** [comment]
Thanks!

**Comment by miyagawa** [comment]
The reason we don't support Time btw is that using Time (without timezone) in API response could lead to an ambiguous semantics, and the time should always be returned with a corresponding timezone.

**Comment by taiki45** [comment]
@miyagawa Oh, that's right. But when I try and look reference a little bit, it seems a normal Ruby `Time` object has timezone.

```
~
✔ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

~
✔ ruby -rjson -e 'puts Time.now.to_json'
"2015-05-05 11:53:58 +0900"
```

Is there a chance of lacking timezone with normal Ruby `Time` object?

**Comment by miyagawa** [comment]
That looks true, and I cannot remember the case where using Time was a bad idea. Seems like it always has a timezone attached to it.

**Comment by taiki45** [comment]
All right. So I'd like to leave this feature as it is, and when we have bad case again, will revert this.

**Pull request merged**
