### PR TITLE
Add block to arg of Representer.property

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by miyagawa** [comment]
Sorry for being late on the issue!

I think I understood the intent of this pull request, but what's the added benefit, other than a little concise code? with the "Worse is Better" approach, I think the current implementation (always requires the method) is much simpler and there's no surprise.

**Comment by taiki45** [comment]
I see. I agree to select the Worse is Better approach to avoid making developers confused.

**Comment by yui-knk** [comment]
@miyagawa  Thanks for your review!

I think

1. In ActiveRecord, declaration method gets block as arguments same as symbol

  ```
class Comment
  include ActiveModel::Validations

  validate :must_be_friends

  def must_be_friends
    errors.add(:base, 'Must be friends to leave a comment') unless commenter.friend_of?(commentee)
  end
end

class Comment
  include ActiveModel::Validations

  validate do
    errors.add(:base, 'Must be friends to leave a comment') unless commenter.friend_of?(commentee)
  end
end
``` 

1. In Ruby world "Diversity is Good"

**Comment by miyagawa** [comment]
> In ActiveRecord, declaration method gets block as arguments same as symbol

Right, but that's not what happens here - AR takes *either* a symbol (for methods) or a block, whereas Garage declaration defines property name as a symbol, which defaults to the current method name.

Actually, Garage already allows `:as` parameter for similar purposes, and the similarity to the block syntax would be a bit confusing.

```
property :name                 # calls "name" method, available as "name" property
property :name, as: "title" # calls "name" method, available as "title" property

property :name do
  ...
end                                   # this PR - calls the block, available as "name" property
```

This `:as` option is closed to Rails ActiveModel's `has_one ... as: `, and while it does not seem to be available in the documentation it looks like, we're using it in some places on production - the similarity would be quite confusing since the first parameter is used as an implementation, not the property name, whereas your PR does otherwise.

**Comment by miyagawa** [comment]
What I mean by this is - whether you like it or not, current intent of `property :foo` is that "`:foo` **field** of this object (i.e. `foo` method) is an external property in Garage" - and it accepts `:as` option to override the **name** of the property, which by default is the same as the field.

What you interpret in this pull request is likely "there is an external `:foo` field in this object and the actual implementation is, by default, `:foo` method (and can be altered using an optional block)". I don't disagree that's a nice way to put it, but that's not consistent with the current implementation.

**Comment by yui-knk** [comment]
@miyagawa  Thanks for your explanation. I understand :). So I will close this PR.

**Pull request closed without merging**
